# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blog de Fer Perales
email: me@ferperales.net
description: "Startup&Coding&Design&Music&More"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.ferperales.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ferperalesm
github_username:  ferperales
permalink: /:year/:month/:title


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-paginate-v2
  - jekyll-seo-tag

pagination:
  enabled: true
  per_page: 5
  permalink: "/page/:num/"
  sort_reverse: true

excerpt_separator: "<!--more-->"
show_excerpts: true

comments: true
disqus:
  shortname: ferperalesnet

google_analytics: UA-152914723-1

author: Fer Perales

twitter:
  username: FerPeralesM
  card: summary

social:
  name: Fer Perales
  links:
    - https://twitter.com/FerPeralesM
    - https://www.linkedin.com/in/FerPerales
    - https://github.com/ferperales

lang: es_MX
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - deploy.sh

sass:
  style: compressed
